# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf7addeaeaf6510a95fc30d16128c43f033cc9d8c62cd69ca5ae54e4bdc9d021ace722ba6c19bd2f0e1145cacced0a8435ea8692e4e039780c1af5a738c251b6

test:
  secret_key_base: 053161d927c9d0666544cc0b435db55c35b168825cdd6ade93913da06cb7b4d6bc506539cc9cd907b80f74381a863c06cfd200493614896be95a7ff1c7f0ed98

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
